# Generated by Django 5.2.7 on 2025-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdur', models.IntegerField()),
                ('cprice', models.FloatField()),
            ],
        ),
    ]
