# Generated by Django 5.2.7 on 2025-10-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
